spring.application.name=AirBnb-App

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/airbnb
spring.datasource.username=pguser
spring.datasource.password=pguser
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



server.servlet.context-path=/api/v1


jwt.secret.key= uwzdeyhcmnrrhzmtakfqc0grzkrztssdpunspjaffnhr45mraqwetxygtspgew34ksttemovjknrrykspxg2zwxzi

frontend.url=http://localhost:8080

stripe.secret.key=sk_test_51UHeJuHAZ6QSWFIdsv0LmI7kMFyLuZnQAoEYfjjSWsmPco5QKDQToTdiVGITIms34GeSn7SBj2sxsHize2jSeQpc00C6M6NzH7



stripe.webhook.secret=whsec_7f38fee39ad4ce808870dab7529807a7b6eda4962e69ba6dbe5d6e92326a88f9